
// This file has been generated by the GUI designer. Do not modify.
namespace BugzillaInterface
{
	public partial class ProductFilterWidget
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment;

		private global::BugzillaInterface.SensitiveTextBox productTextBox;

		private global::Gtk.Label GtkLabel1;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment1;

		private global::BugzillaInterface.SensitiveTextBox componentTextBox;

		private global::Gtk.Label GtkLabel13;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment2;

		private global::BugzillaInterface.SensitiveTextBox versionTextBox;

		private global::Gtk.Label GtkLabel2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BugzillaInterface.ProductFilterWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BugzillaInterface.ProductFilterWidget";
			// Container child BugzillaInterface.ProductFilterWidget.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.productTextBox = new global::BugzillaInterface.SensitiveTextBox ();
			this.productTextBox.Events = ((global::Gdk.EventMask)(256));
			this.productTextBox.Name = "productTextBox";
			this.GtkAlignment.Add (this.productTextBox);
			this.frame4.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Product</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel1;
			this.vbox4.Add (this.frame4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.componentTextBox = new global::BugzillaInterface.SensitiveTextBox ();
			this.componentTextBox.Events = ((global::Gdk.EventMask)(256));
			this.componentTextBox.Name = "componentTextBox";
			this.GtkAlignment1.Add (this.componentTextBox);
			this.frame5.Add (this.GtkAlignment1);
			this.GtkLabel13 = new global::Gtk.Label ();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Component</b>");
			this.GtkLabel13.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel13;
			this.vbox4.Add (this.frame5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.versionTextBox = new global::BugzillaInterface.SensitiveTextBox ();
			this.versionTextBox.Events = ((global::Gdk.EventMask)(256));
			this.versionTextBox.Name = "versionTextBox";
			this.GtkAlignment2.Add (this.versionTextBox);
			this.frame6.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Version</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel2;
			this.vbox4.Add (this.frame6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame6]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
