
// This file has been generated by the GUI designer. Do not modify.
namespace BugzillaInterface
{
	public partial class StringArrayWidget
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.CheckButton enabledCheckbox;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView optionTreeView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BugzillaInterface.StringArrayWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BugzillaInterface.StringArrayWidget";
			// Container child BugzillaInterface.StringArrayWidget.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.enabledCheckbox = new global::Gtk.CheckButton ();
			this.enabledCheckbox.CanFocus = true;
			this.enabledCheckbox.Name = "enabledCheckbox";
			this.enabledCheckbox.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
			this.enabledCheckbox.DrawIndicator = true;
			this.enabledCheckbox.UseUnderline = true;
			this.vbox7.Add (this.enabledCheckbox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.enabledCheckbox]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.optionTreeView = new global::Gtk.TreeView ();
			this.optionTreeView.Sensitive = false;
			this.optionTreeView.CanFocus = true;
			this.optionTreeView.Name = "optionTreeView";
			this.GtkScrolledWindow.Add (this.optionTreeView);
			this.vbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow]));
			w3.Position = 1;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.enabledCheckbox.Toggled += new global::System.EventHandler (this.CheckboxToggled);
		}
	}
}
