
// This file has been generated by the GUI designer. Do not modify.
namespace Frontend
{
	public partial class AddQueryDialog
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Expander expander1;

		private global::Gtk.Label label4;

		private global::Gtk.Label GtkLabel6;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label5;

		private global::Gtk.Entry bugTitleEntry;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox sourceSelector;

		private global::Gtk.Button addSourceButton;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView queryTreeView;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.HBox filterContainer;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label testQueryOutputLabel;

		private global::Gtk.Button testQueryButton;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Frontend.AddQueryDialog
			this.Name = "Frontend.AddQueryDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("dialog1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Frontend.AddQueryDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			// Container child expander1.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xpad = 13;
			this.label4.Xalign = 0f;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("1. Select a source or add a new one.\n2. Set the required parameter for each filter of the query\n3. Test the query to see number of results.\n4. Click \"OK\" to add the Query.\n\nYou'll need to test the query again if you make any changes to the filters.");
			this.expander1.Add (this.label4);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Instructions");
			this.GtkLabel6.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel6;
			this.vbox3.Add (this.expander1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.expander1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 73;
			this.label5.Name = "label5";
			this.label5.Xpad = 13;
			this.label5.Xalign = 0f;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.hbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.bugTitleEntry = new global::Gtk.Entry ();
			this.bugTitleEntry.WidthRequest = 413;
			this.bugTitleEntry.CanFocus = true;
			this.bugTitleEntry.Name = "bugTitleEntry";
			this.bugTitleEntry.IsEditable = true;
			this.bugTitleEntry.InvisibleChar = '●';
			this.hbox4.Add (this.bugTitleEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.bugTitleEntry]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xpad = 13;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Source: ");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.sourceSelector = global::Gtk.ComboBox.NewText ();
			this.sourceSelector.Name = "sourceSelector";
			this.hbox1.Add (this.sourceSelector);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.sourceSelector]));
			w8.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.addSourceButton = new global::Gtk.Button ();
			this.addSourceButton.CanFocus = true;
			this.addSourceButton.Name = "addSourceButton";
			this.addSourceButton.UseUnderline = true;
			// Container child addSourceButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = global::Mono.Unix.Catalog.GetString ("Add New Source");
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.addSourceButton.Add (w9);
			this.hbox1.Add (this.addSourceButton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.addSourceButton]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.queryTreeView = new global::Gtk.TreeView ();
			this.queryTreeView.WidthRequest = 130;
			this.queryTreeView.CanFocus = true;
			this.queryTreeView.Name = "queryTreeView";
			this.GtkScrolledWindow.Add (this.queryTreeView);
			this.GtkAlignment3.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Query Type</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel3;
			this.hbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame1]));
			w22.Position = 0;
			w22.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.filterContainer = new global::Gtk.HBox ();
			this.filterContainer.Name = "filterContainer";
			this.filterContainer.Spacing = 6;
			this.GtkAlignment4.Add (this.filterContainer);
			this.frame2.Add (this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Query Configuration</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel4;
			this.hbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame2]));
			w25.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w26.Position = 3;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.testQueryOutputLabel = new global::Gtk.Label ();
			this.testQueryOutputLabel.Name = "testQueryOutputLabel";
			this.testQueryOutputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Please test the query before adding.");
			this.hbox3.Add (this.testQueryOutputLabel);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.testQueryOutputLabel]));
			w27.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.testQueryButton = new global::Gtk.Button ();
			this.testQueryButton.WidthRequest = 150;
			this.testQueryButton.HeightRequest = 0;
			this.testQueryButton.Sensitive = false;
			this.testQueryButton.CanFocus = true;
			this.testQueryButton.Name = "testQueryButton";
			this.testQueryButton.UseUnderline = true;
			// Container child testQueryButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w29 = new global::Gtk.HBox ();
			w29.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Dnd);
			w29.Add (w30);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w32 = new global::Gtk.Label ();
			w32.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Query");
			w32.UseUnderline = true;
			w29.Add (w32);
			w28.Add (w29);
			this.testQueryButton.Add (w28);
			this.hbox3.Add (this.testQueryButton);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.testQueryButton]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w37.Position = 4;
			w37.Expand = false;
			w37.Fill = false;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(w1[this.vbox3]));
			w38.Position = 0;
			// Internal child Frontend.AddQueryDialog.ActionArea
			global::Gtk.HButtonBox w39 = this.ActionArea;
			w39.Name = "dialog1_ActionArea";
			w39.Spacing = 10;
			w39.BorderWidth = ((uint)(5));
			w39.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w39[this.buttonCancel]));
			w40.Expand = false;
			w40.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w39[this.buttonOk]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 560;
			this.DefaultHeight = 496;
			this.Show ();
			this.sourceSelector.Changed += new global::System.EventHandler (this.ComboBoxChanged);
			this.addSourceButton.Clicked += new global::System.EventHandler (this.AddSourceButtonClicked);
			this.queryTreeView.SelectCursorRow += new global::Gtk.SelectCursorRowHandler (this.FilterSelected);
			this.queryTreeView.RowActivated += new global::Gtk.RowActivatedHandler (this.FilterActivated);
			this.testQueryButton.Clicked += new global::System.EventHandler (this.TestQueryButtonClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.CancelButtonClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OKButtonClicked);
		}
	}
}
