
// This file has been generated by the GUI designer. Do not modify.
namespace Frontend
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action addAction;

		private global::Gtk.Action refreshAction;

		private global::Gtk.Action deleteAction;

		private global::Gtk.Action fetchCommentsAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Toolbar toolbar3;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview1;

		private global::Gtk.Notebook notebook2;

		private global::Gtk.VBox vbox9;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.VBox commentVBox;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView commentEntryBox;

		private global::Gtk.Button commentSendButton;

		private global::Gtk.Label label5;

		private global::Gtk.Table bugPropertyTable;

		private global::Gtk.Label label6;

		private global::Gtk.Statusbar statusbar1;

		private global::Gtk.ProgressBar progressbar1;

		private global::Gtk.Label statusLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Frontend.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("Add Query"), global::Mono.Unix.Catalog.GetString ("Add Queries"), "gtk-add");
			this.addAction.HideIfEmpty = false;
			this.addAction.IsImportant = true;
			this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Query");
			w1.Add (this.addAction, "<Control><Alt><Meta>n");
			this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("Refresh Queries"), global::Mono.Unix.Catalog.GetString ("Refresh Queries"), "gtk-refresh");
			this.refreshAction.HideIfEmpty = false;
			this.refreshAction.IsImportant = true;
			this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Refresh Queries");
			w1.Add (this.refreshAction, null);
			this.deleteAction = new global::Gtk.Action ("deleteAction", global::Mono.Unix.Catalog.GetString ("Delete Query"), global::Mono.Unix.Catalog.GetString ("Delete Query"), "gtk-delete");
			this.deleteAction.HideIfEmpty = false;
			this.deleteAction.IsImportant = true;
			this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete Query");
			w1.Add (this.deleteAction, null);
			this.fetchCommentsAction = new global::Gtk.Action ("fetchCommentsAction", global::Mono.Unix.Catalog.GetString ("Fetch Comments"), null, "gtk-sort-descending");
			this.fetchCommentsAction.IsImportant = true;
			this.fetchCommentsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fetch Comments");
			w1.Add (this.fetchCommentsAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Frontend.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Splatter - Query View");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Frontend.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar3'><toolitem name='addAction' action='addAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='deleteAction' action='deleteAction'/><toolitem name='fetchCommentsAction' action='fetchCommentsAction'/></toolbar></ui>");
			this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
			this.toolbar3.Name = "toolbar3";
			this.toolbar3.ShowArrow = false;
			this.toolbar3.IconSize = ((global::Gtk.IconSize)(3));
			this.vbox1.Add (this.toolbar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 403;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow]));
			w4.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.commentVBox = new global::Gtk.VBox ();
			this.commentVBox.Name = "commentVBox";
			this.commentVBox.Spacing = 6;
			w5.Add (this.commentVBox);
			this.scrolledwindow2.Add (w5);
			this.vbox9.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.scrolledwindow2]));
			w8.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xpad = 9;
			this.label7.Xalign = 0f;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Post Comment:");
			this.vbox10.Add (this.label7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label7]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.commentEntryBox = new global::Gtk.TextView ();
			this.commentEntryBox.HeightRequest = 60;
			this.commentEntryBox.CanFocus = true;
			this.commentEntryBox.Name = "commentEntryBox";
			this.GtkScrolledWindow1.Add (this.commentEntryBox);
			this.hbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GtkScrolledWindow1]));
			w11.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.commentSendButton = new global::Gtk.Button ();
			this.commentSendButton.Sensitive = false;
			this.commentSendButton.CanFocus = true;
			this.commentSendButton.Name = "commentSendButton";
			this.commentSendButton.UseUnderline = true;
			// Container child commentSendButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-network", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Send");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.commentSendButton.Add (w12);
			this.hbox4.Add (this.commentSendButton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.commentSendButton]));
			w20.Position = 1;
			w20.Expand = false;
			this.vbox10.Add (this.hbox4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox4]));
			w21.Position = 1;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vbox10]));
			w22.Position = 1;
			w22.Expand = false;
			this.notebook2.Add (this.vbox9);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xpad = 16;
			this.label5.Ypad = 3;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Comments");
			this.notebook2.SetTabLabel (this.vbox9, this.label5);
			this.label5.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.bugPropertyTable = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.bugPropertyTable.Name = "bugPropertyTable";
			this.bugPropertyTable.RowSpacing = ((uint)(6));
			this.bugPropertyTable.ColumnSpacing = ((uint)(6));
			this.notebook2.Add (this.bugPropertyTable);
			global::Gtk.Notebook.NotebookChild w24 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.bugPropertyTable]));
			w24.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xpad = 16;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Bug Details");
			this.notebook2.SetTabLabel (this.bugPropertyTable, this.label6);
			this.label6.ShowAll ();
			this.hpaned1.Add (this.notebook2);
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
			w26.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			this.statusbar1.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.progressbar1]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.statusLabel = new global::Gtk.Label ();
			this.statusLabel.Name = "statusLabel";
			this.statusLabel.Xpad = 13;
			this.statusLabel.Xalign = 0f;
			this.statusbar1.Add (this.statusLabel);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.statusLabel]));
			w28.Position = 2;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 751;
			this.DefaultHeight = 658;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.addAction.Activated += new global::System.EventHandler (this.AddNewQueryClicked);
			this.refreshAction.Activated += new global::System.EventHandler (this.RefreshQueriesBuggonClicked);
			this.deleteAction.Activated += new global::System.EventHandler (this.DeleteQuery);
			this.fetchCommentsAction.Activated += new global::System.EventHandler (this.FetchCommentsActivated);
			this.commentSendButton.Activated += new global::System.EventHandler (this.PostCommentClicked);
			this.commentSendButton.Clicked += new global::System.EventHandler (this.PostCommentClicked2);
		}
	}
}
