// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Frontend {
    
    
    public partial class AddQueryDialog {
        
        private Gtk.VBox vbox3;
        
        private Gtk.Expander expander1;
        
        private Gtk.Label label4;
        
        private Gtk.Label GtkLabel6;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label5;
        
        private Gtk.Entry bugTitleEntry;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label3;
        
        private Gtk.ComboBox sourceSelector;
        
        private Gtk.Button addSourceButton;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView queryTreeView;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment4;
        
        private Gtk.HBox filterContainer;
        
        private Gtk.Label GtkLabel4;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label testQueryOutputLabel;
        
        private Gtk.Button testQueryButton;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Frontend.AddQueryDialog
            this.Name = "Frontend.AddQueryDialog";
            this.Title = Mono.Unix.Catalog.GetString("dialog1");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Internal child Frontend.AddQueryDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            // Container child expander1.Gtk.Container+ContainerChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xpad = 13;
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("1. Select a source or add a new one.\n2. Set the required parameter for each filter of the query\n3. Test the query to see number of results.\n4. Click \"OK\" to add the Query.\n\nYou'll need to test the query again if you make any changes to the filters.");
            this.expander1.Add(this.label4);
            this.GtkLabel6 = new Gtk.Label();
            this.GtkLabel6.Name = "GtkLabel6";
            this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("Instructions");
            this.GtkLabel6.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel6;
            this.vbox3.Add(this.expander1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.expander1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.WidthRequest = 73;
            this.label5.Name = "label5";
            this.label5.Xpad = 13;
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.hbox4.Add(this.label5);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox4[this.label5]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.bugTitleEntry = new Gtk.Entry();
            this.bugTitleEntry.WidthRequest = 413;
            this.bugTitleEntry.CanFocus = true;
            this.bugTitleEntry.Name = "bugTitleEntry";
            this.bugTitleEntry.IsEditable = true;
            this.bugTitleEntry.InvisibleChar = '●';
            this.hbox4.Add(this.bugTitleEntry);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox4[this.bugTitleEntry]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox3.Add(this.hbox4);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xpad = 13;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Source: ");
            this.hbox1.Add(this.label3);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.label3]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.sourceSelector = Gtk.ComboBox.NewText();
            this.sourceSelector.Name = "sourceSelector";
            this.hbox1.Add(this.sourceSelector);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.sourceSelector]));
            w8.Position = 1;
            // Container child hbox1.Gtk.Box+BoxChild
            this.addSourceButton = new Gtk.Button();
            this.addSourceButton.CanFocus = true;
            this.addSourceButton.Name = "addSourceButton";
            this.addSourceButton.UseUnderline = true;
            // Container child addSourceButton.Gtk.Container+ContainerChild
            Gtk.Alignment w9 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w10 = new Gtk.HBox();
            w10.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w11 = new Gtk.Image();
            w11.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w10.Add(w11);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w13 = new Gtk.Label();
            w13.LabelProp = Mono.Unix.Catalog.GetString("Add New Source");
            w13.UseUnderline = true;
            w10.Add(w13);
            w9.Add(w10);
            this.addSourceButton.Add(w9);
            this.hbox1.Add(this.addSourceButton);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox1[this.addSourceButton]));
            w17.Position = 2;
            w17.Expand = false;
            w17.Fill = false;
            this.vbox3.Add(this.hbox1);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
            w18.Position = 2;
            w18.Expand = false;
            w18.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.queryTreeView = new Gtk.TreeView();
            this.queryTreeView.WidthRequest = 130;
            this.queryTreeView.CanFocus = true;
            this.queryTreeView.Name = "queryTreeView";
            this.GtkScrolledWindow.Add(this.queryTreeView);
            this.GtkAlignment3.Add(this.GtkScrolledWindow);
            this.frame1.Add(this.GtkAlignment3);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Query Type</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel3;
            this.hbox2.Add(this.frame1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox2[this.frame1]));
            w22.Position = 0;
            w22.Expand = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment4.Name = "GtkAlignment4";
            this.GtkAlignment4.LeftPadding = ((uint)(12));
            // Container child GtkAlignment4.Gtk.Container+ContainerChild
            this.filterContainer = new Gtk.HBox();
            this.filterContainer.Name = "filterContainer";
            this.filterContainer.Spacing = 6;
            this.GtkAlignment4.Add(this.filterContainer);
            this.frame2.Add(this.GtkAlignment4);
            this.GtkLabel4 = new Gtk.Label();
            this.GtkLabel4.Name = "GtkLabel4";
            this.GtkLabel4.LabelProp = Mono.Unix.Catalog.GetString("<b>Query Configuration</b>");
            this.GtkLabel4.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel4;
            this.hbox2.Add(this.frame2);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox2[this.frame2]));
            w25.Position = 1;
            this.vbox3.Add(this.hbox2);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
            w26.Position = 3;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.testQueryOutputLabel = new Gtk.Label();
            this.testQueryOutputLabel.Name = "testQueryOutputLabel";
            this.testQueryOutputLabel.LabelProp = Mono.Unix.Catalog.GetString("Please test the query before adding.");
            this.hbox3.Add(this.testQueryOutputLabel);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox3[this.testQueryOutputLabel]));
            w27.Position = 0;
            // Container child hbox3.Gtk.Box+BoxChild
            this.testQueryButton = new Gtk.Button();
            this.testQueryButton.WidthRequest = 150;
            this.testQueryButton.HeightRequest = 0;
            this.testQueryButton.Sensitive = false;
            this.testQueryButton.CanFocus = true;
            this.testQueryButton.Name = "testQueryButton";
            this.testQueryButton.UseUnderline = true;
            // Container child testQueryButton.Gtk.Container+ContainerChild
            Gtk.Alignment w28 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w29 = new Gtk.HBox();
            w29.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w30 = new Gtk.Image();
            w30.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Dnd, 32);
            w29.Add(w30);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w32 = new Gtk.Label();
            w32.LabelProp = Mono.Unix.Catalog.GetString("Test Query");
            w32.UseUnderline = true;
            w29.Add(w32);
            w28.Add(w29);
            this.testQueryButton.Add(w28);
            this.hbox3.Add(this.testQueryButton);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox3[this.testQueryButton]));
            w36.Position = 1;
            w36.Expand = false;
            w36.Fill = false;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w37.Position = 4;
            w37.Expand = false;
            w37.Fill = false;
            w1.Add(this.vbox3);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(w1[this.vbox3]));
            w38.Position = 0;
            // Internal child Frontend.AddQueryDialog.ActionArea
            Gtk.HButtonBox w39 = this.ActionArea;
            w39.Name = "dialog1_ActionArea";
            w39.Spacing = 10;
            w39.BorderWidth = ((uint)(5));
            w39.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w40 = ((Gtk.ButtonBox.ButtonBoxChild)(w39[this.buttonCancel]));
            w40.Expand = false;
            w40.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.Sensitive = false;
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w41 = ((Gtk.ButtonBox.ButtonBoxChild)(w39[this.buttonOk]));
            w41.Position = 1;
            w41.Expand = false;
            w41.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 560;
            this.DefaultHeight = 496;
            this.Show();
            this.sourceSelector.Changed += new System.EventHandler(this.ComboBoxChanged);
            this.addSourceButton.Clicked += new System.EventHandler(this.AddSourceButtonClicked);
            this.queryTreeView.SelectCursorRow += new Gtk.SelectCursorRowHandler(this.FilterSelected);
            this.queryTreeView.RowActivated += new Gtk.RowActivatedHandler(this.FilterActivated);
            this.testQueryButton.Clicked += new System.EventHandler(this.TestQueryButtonClicked);
            this.buttonCancel.Clicked += new System.EventHandler(this.CancelButtonClicked);
            this.buttonOk.Clicked += new System.EventHandler(this.OKButtonClicked);
        }
    }
}
