// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Frontend {
    
    
    public partial class NewSourceDialog {
        
        private Gtk.VBox vbox4;
        
        private Gtk.Table table1;
        
        private Gtk.ComboBox combobox2;
        
        private Gtk.Label label10;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Entry nameEntry;
        
        private Gtk.Entry passwordEntry;
        
        private Gtk.Entry proxyEntry;
        
        private Gtk.Entry urlEntry;
        
        private Gtk.Entry usernameEntry;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label statusLabel;
        
        private Gtk.Button verifyButton;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Frontend.NewSourceDialog
            this.Name = "Frontend.NewSourceDialog";
            this.Title = Mono.Unix.Catalog.GetString("dialog1");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Internal child Frontend.NewSourceDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.combobox2 = Gtk.ComboBox.NewText();
            this.combobox2.AppendText(Mono.Unix.Catalog.GetString("Bugzilla"));
            this.combobox2.Name = "combobox2";
            this.combobox2.Active = 0;
            this.table1.Add(this.combobox2);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.combobox2]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xpad = 13;
            this.label10.Xalign = 0F;
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xpad = 13;
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Source Type:");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xpad = 13;
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Url:");
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xpad = 13;
            this.label7.Ypad = 3;
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Username:");
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w6.TopAttach = ((uint)(3));
            w6.BottomAttach = ((uint)(4));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xpad = 13;
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Password:");
            this.table1.Add(this.label8);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
            w7.TopAttach = ((uint)(4));
            w7.BottomAttach = ((uint)(5));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xpad = 13;
            this.label9.Xalign = 0F;
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Proxy:");
            this.table1.Add(this.label9);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
            w8.TopAttach = ((uint)(5));
            w8.BottomAttach = ((uint)(6));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.nameEntry = new Gtk.Entry();
            this.nameEntry.CanFocus = true;
            this.nameEntry.Name = "nameEntry";
            this.nameEntry.IsEditable = true;
            this.nameEntry.InvisibleChar = '●';
            this.table1.Add(this.nameEntry);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.nameEntry]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.passwordEntry = new Gtk.Entry();
            this.passwordEntry.CanFocus = true;
            this.passwordEntry.Name = "passwordEntry";
            this.passwordEntry.IsEditable = true;
            this.passwordEntry.Visibility = false;
            this.passwordEntry.InvisibleChar = '●';
            this.table1.Add(this.passwordEntry);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.passwordEntry]));
            w10.TopAttach = ((uint)(4));
            w10.BottomAttach = ((uint)(5));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.proxyEntry = new Gtk.Entry();
            this.proxyEntry.CanFocus = true;
            this.proxyEntry.Name = "proxyEntry";
            this.proxyEntry.IsEditable = true;
            this.proxyEntry.InvisibleChar = '●';
            this.table1.Add(this.proxyEntry);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.proxyEntry]));
            w11.TopAttach = ((uint)(5));
            w11.BottomAttach = ((uint)(6));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.urlEntry = new Gtk.Entry();
            this.urlEntry.CanFocus = true;
            this.urlEntry.Name = "urlEntry";
            this.urlEntry.IsEditable = true;
            this.urlEntry.InvisibleChar = '●';
            this.table1.Add(this.urlEntry);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.urlEntry]));
            w12.TopAttach = ((uint)(2));
            w12.BottomAttach = ((uint)(3));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.usernameEntry = new Gtk.Entry();
            this.usernameEntry.CanFocus = true;
            this.usernameEntry.Name = "usernameEntry";
            this.usernameEntry.IsEditable = true;
            this.usernameEntry.InvisibleChar = '●';
            this.table1.Add(this.usernameEntry);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.usernameEntry]));
            w13.TopAttach = ((uint)(3));
            w13.BottomAttach = ((uint)(4));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox4.Add(this.table1);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox4[this.table1]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.statusLabel = new Gtk.Label();
            this.statusLabel.Name = "statusLabel";
            this.statusLabel.Xalign = 1F;
            this.statusLabel.LabelProp = Mono.Unix.Catalog.GetString("Status: <b>Unverified</b>");
            this.statusLabel.UseMarkup = true;
            this.hbox3.Add(this.statusLabel);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox3[this.statusLabel]));
            w15.Position = 0;
            // Container child hbox3.Gtk.Box+BoxChild
            this.verifyButton = new Gtk.Button();
            this.verifyButton.WidthRequest = 120;
            this.verifyButton.HeightRequest = 40;
            this.verifyButton.CanFocus = true;
            this.verifyButton.Name = "verifyButton";
            this.verifyButton.UseUnderline = true;
            // Container child verifyButton.Gtk.Container+ContainerChild
            Gtk.Alignment w16 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w17 = new Gtk.HBox();
            w17.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w18 = new Gtk.Image();
            w18.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w17.Add(w18);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w20 = new Gtk.Label();
            w20.LabelProp = Mono.Unix.Catalog.GetString("Verify");
            w20.UseUnderline = true;
            w17.Add(w20);
            w16.Add(w17);
            this.verifyButton.Add(w16);
            this.hbox3.Add(this.verifyButton);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox3[this.verifyButton]));
            w24.Position = 1;
            w24.Expand = false;
            w24.Fill = false;
            this.vbox4.Add(this.hbox3);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
            w25.Position = 1;
            w25.Expand = false;
            w25.Fill = false;
            w1.Add(this.vbox4);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(w1[this.vbox4]));
            w26.Position = 0;
            w26.Expand = false;
            w26.Fill = false;
            // Internal child Frontend.NewSourceDialog.ActionArea
            Gtk.HButtonBox w27 = this.ActionArea;
            w27.Name = "dialog1_ActionArea";
            w27.Spacing = 10;
            w27.BorderWidth = ((uint)(5));
            w27.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w28 = ((Gtk.ButtonBox.ButtonBoxChild)(w27[this.buttonCancel]));
            w28.Expand = false;
            w28.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.Sensitive = false;
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w29 = ((Gtk.ButtonBox.ButtonBoxChild)(w27[this.buttonOk]));
            w29.Position = 1;
            w29.Expand = false;
            w29.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 350;
            this.DefaultHeight = 289;
            this.Show();
            this.verifyButton.Clicked += new System.EventHandler(this.VerifyButtonClicked);
            this.buttonCancel.Clicked += new System.EventHandler(this.CancelButtonClicked);
            this.buttonOk.Clicked += new System.EventHandler(this.OKButtonClicked);
        }
    }
}
