
// This file has been generated by the GUI designer. Do not modify.
namespace Frontend
{
	public partial class AddQueryDialog
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label5;

		private global::Gtk.Entry bugTitleEntry;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox sourceSelector;

		private global::Gtk.Button addSourceButton;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView queryTreeView;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.HBox filterContainer;

		private global::Gtk.Label label6;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label testQueryOutputLabel;

		private global::Gtk.Button testQueryButton;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Frontend.AddQueryDialog
			this.Name = "Frontend.AddQueryDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add new Query");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Frontend.AddQueryDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 73;
			this.label5.Name = "label5";
			this.label5.Xpad = 13;
			this.label5.Xalign = 0f;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.hbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.bugTitleEntry = new global::Gtk.Entry ();
			this.bugTitleEntry.WidthRequest = 413;
			this.bugTitleEntry.CanFocus = true;
			this.bugTitleEntry.Name = "bugTitleEntry";
			this.bugTitleEntry.IsEditable = true;
			this.bugTitleEntry.InvisibleChar = '●';
			this.hbox4.Add (this.bugTitleEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.bugTitleEntry]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xpad = 13;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Source: ");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.sourceSelector = global::Gtk.ComboBox.NewText ();
			this.sourceSelector.Name = "sourceSelector";
			this.hbox1.Add (this.sourceSelector);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.sourceSelector]));
			w6.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.addSourceButton = new global::Gtk.Button ();
			this.addSourceButton.CanFocus = true;
			this.addSourceButton.Name = "addSourceButton";
			this.addSourceButton.UseUnderline = true;
			// Container child addSourceButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = global::Mono.Unix.Catalog.GetString ("Add New Source");
			w11.UseUnderline = true;
			w8.Add (w11);
			w7.Add (w8);
			this.addSourceButton.Add (w7);
			this.hbox1.Add (this.addSourceButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.addSourceButton]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.HeightRequest = 260;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.queryTreeView = new global::Gtk.TreeView ();
			this.queryTreeView.WidthRequest = 130;
			this.queryTreeView.CanFocus = true;
			this.queryTreeView.Name = "queryTreeView";
			this.GtkScrolledWindow.Add (this.queryTreeView);
			this.GtkAlignment3.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Filter Type</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel3;
			this.hbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame1]));
			w20.Position = 0;
			w20.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.filterContainer = new global::Gtk.HBox ();
			this.filterContainer.Name = "filterContainer";
			this.filterContainer.Spacing = 6;
			// Container child filterContainer.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Instructions:\n\n1. Select a source or add a new one.\n2. Double click on a filter to configure it.\n3. Test the query to see number of results.\n4. Click \"OK\" to add the Query.\n\nYou'll need to test the query again if you make any changes to the filters.");
			this.label6.Wrap = true;
			this.filterContainer.Add (this.label6);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.filterContainer[this.label6]));
			w21.Position = 0;
			this.GtkAlignment4.Add (this.filterContainer);
			this.frame2.Add (this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Filter Configuration</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel4;
			this.hbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame2]));
			w24.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.testQueryOutputLabel = new global::Gtk.Label ();
			this.testQueryOutputLabel.Name = "testQueryOutputLabel";
			this.testQueryOutputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Please test the query before adding.");
			this.hbox3.Add (this.testQueryOutputLabel);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.testQueryOutputLabel]));
			w26.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.testQueryButton = new global::Gtk.Button ();
			this.testQueryButton.WidthRequest = 150;
			this.testQueryButton.HeightRequest = 0;
			this.testQueryButton.Sensitive = false;
			this.testQueryButton.CanFocus = true;
			this.testQueryButton.Name = "testQueryButton";
			this.testQueryButton.UseUnderline = true;
			// Container child testQueryButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w27 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w28 = new global::Gtk.HBox ();
			w28.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w29 = new global::Gtk.Image ();
			w29.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Dnd);
			w28.Add (w29);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w31 = new global::Gtk.Label ();
			w31.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Query");
			w31.UseUnderline = true;
			w28.Add (w31);
			w27.Add (w28);
			this.testQueryButton.Add (w27);
			this.hbox3.Add (this.testQueryButton);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.testQueryButton]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(w1[this.vbox3]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Internal child Frontend.AddQueryDialog.ActionArea
			global::Gtk.HButtonBox w38 = this.ActionArea;
			w38.Name = "dialog1_ActionArea";
			w38.Spacing = 10;
			w38.BorderWidth = ((uint)(5));
			w38.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w38[this.buttonCancel]));
			w39.Expand = false;
			w39.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w38[this.buttonOk]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 611;
			this.DefaultHeight = 469;
			this.Show ();
			this.sourceSelector.Changed += new global::System.EventHandler (this.ComboBoxChanged);
			this.addSourceButton.Clicked += new global::System.EventHandler (this.AddSourceButtonClicked);
			this.queryTreeView.SelectCursorRow += new global::Gtk.SelectCursorRowHandler (this.FilterSelected);
			this.queryTreeView.RowActivated += new global::Gtk.RowActivatedHandler (this.FilterActivated);
			this.testQueryButton.Clicked += new global::System.EventHandler (this.TestQueryButtonClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.CancelButtonClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OKButtonClicked);
		}
	}
}
